"""Core package for supersingular graph, sandpile, and image-backed simulations."""

from .compiled import (
    build_compiled_workspace_index,
    CompiledCarrierCapacity,
    CompiledWorkspaceIndex,
    inspect_compiled_ternlsb_capacity,
)
from .dag import (
    AddGrainNode,
    ApplyTernLSBProgramNode,
    BuildCanonicalStateIndexNode,
    BuildCausalGraphIndexNode,
    BuildCompiledWorkspaceIndexNode,
    BuildHypergraphCandidateIndexNode,
    BuildProductionPointerNode,
    BuildStegoCycleEventIndexNode,
    BuildUpdateEventIndexNode,
    CausalDependencyRecord,
    CausalGraphIndex,
    Dag,
    DagContext,
    DeduplicateStateTreeNode,
    DagNode,
    DecodeTernLSBNode,
    DescribeTernLSBProgramNode,
    EmitOntologyRecordNode,
    EncodeTernLSBNode,
    ExtractSandpileFeaturesNode,
    GenerateRecursiveSubtreeNode,
    GraphSandpileOntologyPipeline,
    GraphToSandpilePipeline,
    HyperedgeCandidateRecord,
    HypergraphCandidateIndex,
    ProductionPointerRecord,
    ProjectSandpileToImageNode,
    ProjectConfigurationToImageNode,
    RebindConfigurationNode,
    RecursiveStateTreePipeline,
    RegularSandpileStatePipeline,
    ReviewArchivedStateChainNode,
    StabilizeConfigurationNode,
    StegoSandpileCyclePipeline,
    UpdateEventIndex,
    UpdateEventRecord,
)
from .eisenstein import (
    axial_distance,
    build_lattice_order as build_eisenstein_lattice_order,
    centered_configuration as centered_eisenstein_configuration,
    configuration_from_program_text as eisenstein_configuration_from_program_text,
    configuration_from_site_map as eisenstein_configuration_from_site_map,
    config_from_points as eisenstein_config_from_points,
    config_from_sites as eisenstein_config_from_sites,
    corner_sites as eisenstein_corner_sites,
    corner_wedge_config as eisenstein_corner_wedge_config,
    EISENSTEIN_NEIGHBOR_OFFSETS,
    eisenstein_vertex,
    expand_program_phase as expand_eisenstein_program_phase,
    make_eisenstein_graph,
    parse_program_string as parse_eisenstein_program_string,
)
from .graph import (
    add_chip,
    configuration_signature,
    Edge,
    LaplacianData,
    rebind_configuration,
    sandpile_features,
    SandpileConfiguration,
    SandpileGroupInvariant,
    SandpileModel,
    StabilizationResult,
    stabilize_configuration,
    ToppleRecord,
    UndirectedGraph,
)
from .netpbm import NetpbmImage, read_netpbm, write_netpbm
from .programs import ProgramCatalog, ProgramDescription, describe_ternlsb_execution
from .regular import centered_configuration, make_grid_graph
from .simulation import (
    ArchivedState,
    ArchivedStateChain,
    BranchPolicy,
    CenteredSeedRewriteRule,
    CenterGrainRewriteRule,
    ChainReview,
    ChainReviewStep,
    CanonicalStateIndex,
    CanonicalStateRecord,
    DedupeSummary,
    LowestGrainRewriteRule,
    RewriteRule,
    build_canonical_state_index,
    deduplicate_state_tree,
    generate_successor_subtree_from_stem,
    ImageStateSurface,
    list_descendant_leaf_paths,
    load_archived_state_chain,
    read_state_reference,
    resolve_rewrite_rule,
    resolve_state_image_path,
    review_archived_state_chain,
    SimulationWorkspace,
    StateReference,
    TreeGenerationSummary,
    TreeLevelSummary,
    clone_surface,
    generate_successor_chain,
    generate_successor_tree,
    initialize_identity_surface,
    summarize_archived_tree,
    succ,
    stabilize_surface,
    surface_state_id,
    surface_signature,
)
from .selfcheck import run_selfcheck, SelfCheckReport
from .supersingular import (
    build_supersingular_isogeny_graph,
    estimate_supersingular_vertex_count,
    SupersingularIsogenyGraphSpec,
    supersingular_delta_configuration,
    supersingular_vertex,
)
from .ternlsb import (
    apply_ternlsb_program,
    decode_ternlsb_program,
    encode_ternlsb_program,
    ternlsb_capacity,
    TernLSBExecutionRecord,
    TernLSBProgram,
)
__all__ = [
    "AddGrainNode",
    "ApplyTernLSBProgramNode",
    "ArchivedState",
    "ArchivedStateChain",
    "add_chip",
    "animate_auto_walk",
    "animate_chain",
    "animate_leaf_walk",
    "axial_distance",
    "BranchPolicy",
    "BuildCanonicalStateIndexNode",
    "BuildCausalGraphIndexNode",
    "BuildCompiledWorkspaceIndexNode",
    "BuildHypergraphCandidateIndexNode",
    "BuildProductionPointerNode",
    "BuildStegoCycleEventIndexNode",
    "BuildUpdateEventIndexNode",
    "build_canonical_state_index",
    "build_chain_frame",
    "build_supersingular_isogeny_graph",
    "CenteredSeedRewriteRule",
    "CenterGrainRewriteRule",
    "CanonicalStateIndex",
    "CanonicalStateRecord",
    "ChainReview",
    "ChainReviewStep",
    "CausalDependencyRecord",
    "CausalGraphIndex",
    "clone_surface",
    "CompiledCarrierCapacity",
    "CompiledWorkspaceIndex",
    "configuration_signature",
    "build_compiled_workspace_index",
    "Dag",
    "DagContext",
    "DeduplicateStateTreeNode",
    "DagNode",
    "DecodeTernLSBNode",
    "DescribeTernLSBProgramNode",
    "Edge",
    "EncodeTernLSBNode",
    "EmitOntologyRecordNode",
    "estimate_supersingular_vertex_count",
    "ExtractSandpileFeaturesNode",
    "GenerateRecursiveSubtreeNode",
    "GraphSandpileOntologyPipeline",
    "GraphToSandpilePipeline",
    "HyperedgeCandidateRecord",
    "HypergraphCandidateIndex",
    "inspect_compiled_ternlsb_capacity",
    "ProductionPointerRecord",
    "ProgramCatalog",
    "ProgramDescription",
    "DedupeSummary",
    "deduplicate_state_tree",
    "generate_successor_subtree_from_stem",
    "ImageStateSurface",
    "LaplacianData",
    "LowestGrainRewriteRule",
    "load_archived_state_chain",
    "list_descendant_leaf_paths",
    "nearest_branching_anchor",
    "NetpbmImage",
    "ProjectSandpileToImageNode",
    "ProjectConfigurationToImageNode",
    "RebindConfigurationNode",
    "RecursiveStateTreePipeline",
    "RegularSandpileStatePipeline",
    "read_state_reference",
    "rebind_configuration",
    "resolve_rewrite_rule",
    "related_leaf_walks",
    "render_surface_text",
    "resolve_state_image_path",
    "review_archived_state_chain",
    "ReviewArchivedStateChainNode",
    "centered_configuration",
    "centered_eisenstein_configuration",
    "SandpileConfiguration",
    "SandpileGroupInvariant",
    "SandpileModel",
    "SimulationWorkspace",
    "SelfCheckReport",
    "StegoSandpileCyclePipeline",
    "summarize_archived_tree",
    "sandpile_features",
    "StabilizationResult",
    "stabilize_configuration",
    "StabilizeConfigurationNode",
    "StateReference",
    "succ",
    "supersingular_delta_configuration",
    "SupersingularIsogenyGraphSpec",
    "supersingular_vertex",
    "surface_state_id",
    "TernLSBExecutionRecord",
    "TernLSBProgram",
    "ToppleRecord",
    "TreeGenerationSummary",
    "TreeLevelSummary",
    "UndirectedGraph",
    "UpdateEventIndex",
    "UpdateEventRecord",
    "RewriteRule",
    "apply_ternlsb_program",
    "describe_ternlsb_execution",
    "decode_ternlsb_program",
    "encode_ternlsb_program",
    "EISENSTEIN_NEIGHBOR_OFFSETS",
    "eisenstein_config_from_points",
    "eisenstein_config_from_sites",
    "eisenstein_configuration_from_program_text",
    "eisenstein_configuration_from_site_map",
    "eisenstein_corner_sites",
    "eisenstein_corner_wedge_config",
    "eisenstein_vertex",
    "expand_eisenstein_program_phase",
    "make_eisenstein_graph",
    "make_grid_graph",
    "parse_eisenstein_program_string",
    "read_netpbm",
    "generate_successor_chain",
    "generate_successor_tree",
    "initialize_identity_surface",
    "surface_signature",
    "run_selfcheck",
    "stabilize_surface",
    "ternlsb_capacity",
    "build_eisenstein_lattice_order",
    "write_netpbm",
]

_VIEWER_EXPORTS = {
    "animate_auto_walk",
    "animate_chain",
    "animate_leaf_walk",
    "build_chain_frame",
    "nearest_branching_anchor",
    "related_leaf_walks",
    "render_surface_text",
}


def __getattr__(name: str):
    if name in _VIEWER_EXPORTS:
        from . import viewer

        return getattr(viewer, name)
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
